"""模块 → 用例文件映射（report.py 覆盖矩阵核对的机器可读基线）。

与 coverage.md 的人类可读基线一一对应；新增 live 用例文件时同步更新。
"""

MODULE_FILES: dict[str, list[str]] = {
    "core/executor": ["test_01_execution.py"],
    "core/budget": ["test_01_execution.py"],
    "core/fanout": ["test_01_execution.py"],
    "core/plan": ["test_01_execution.py"],
    "core/spawn": ["test_01_execution.py"],
    "core/simulation": ["test_01_execution.py"],
    "core/recovery": ["test_01_execution.py"],
    "core/interrupt": ["test_01_execution.py", "test_08_approval.py"],
    "core/state": ["test_02_state_patch.py"],
    "core/patch_chain": ["test_02_state_patch.py"],
    "core/state_machine": ["test_02_state_patch.py"],
    "core/storage": ["test_03_storage.py"],
    "core/storage_memory": ["test_03_storage.py"],
    "core/storage_sqlite": ["test_03_storage.py"],
    "core/storage_postgres": ["test_03_storage.py"],
    "core/chain_rebase": ["test_03_storage.py"],
    "core/events": ["test_04_events.py"],
    "core/event_types": ["test_04_events.py"],
    "core/round_steps": ["test_04_events.py"],
    "core/logging": ["test_04_events.py", "test_22_adversarial.py"],
    "llm": ["test_05_llm_full.py"],
    "core/knowledge_signals": ["test_06_self_learning.py"],
    "core/evolution": ["test_06_self_learning.py"],
    "core/knowledge_gate": ["test_06_self_learning.py"],
    "core/rules": ["test_06_self_learning.py"],
    "core/schema_validator": ["test_06_self_learning.py"],
    "core/scoring": ["test_06_self_learning.py"],
    "core/review": ["test_06_self_learning.py"],
    "core/assembly": ["test_07_assembly.py"],
    "core/context": ["test_07_assembly.py"],
    "core/approval": ["test_08_approval.py"],
    "core/review_card": ["test_08_approval.py"],
    "core/tool_pipeline": ["test_09_tools_security.py"],
    "core/permissions": ["test_09_tools_security.py", "test_22_adversarial.py"],
    "core/sandbox": ["test_09_tools_security.py", "test_22_adversarial.py"],
    "core/declarative_tools": ["test_09_tools_security.py"],
    "core/tool_orchestrator": ["test_09_tools_security.py"],
    "core/tool_vetting": ["test_09_tools_security.py", "test_22_adversarial.py"],
    "core/builder": ["test_09_tools_security.py"],
    "core/environments": ["test_09_tools_security.py"],
    "core/introspection": ["test_10_self_evolution.py"],
    "core/self_tools": ["test_10_self_evolution.py"],
    "core/self_proposal": ["test_10_self_evolution.py"],
    "core/self_application": ["test_10_self_evolution.py", "test_22_adversarial.py"],
    "core/ui_schema": ["test_10_self_evolution.py"],
    "core/runtime": ["test_11_runtime.py"],
    "core/seeds": ["test_12_seeds.py"],
    "seeds/boot": ["test_12_seeds.py"],
    "core/graph": ["test_13_graph_full.py"],
    "core/registry": ["test_13_graph_full.py"],
    "core/harness": ["test_13_graph_full.py"],
    "core/memory": ["test_14_memory.py"],
    "core/workflow": ["test_15_workflow.py"],
    "core/knowledge_set": ["test_16_knowledge_full.py"],
    "core/retrieval": ["test_16_knowledge_full.py"],
    "core/tuning": ["test_17_tuning.py"],
    "core/tiers": ["test_17_tuning.py"],
    "core/mcp_client": ["test_18_mcp_full.py", "test_22_adversarial.py"],
    "core/security": ["test_19_data_contracts.py", "test_22_adversarial.py"],
}
