export { ConsolePanel } from './ConsolePanel';
export { activateConsole } from './activate';
export { RegistrySection } from './sections/RegistrySection';
export { TaskSection } from './sections/TaskSection';
export { LedgerSection } from './sections/LedgerSection';
export { BackupSection } from './sections/BackupSection';
export { AuditSection } from './sections/AuditSection';
export { LifecycleSection } from './sections/LifecycleSection';
export { VoiceSection } from './sections/VoiceSection';
export { AppearanceSection } from './sections/AppearanceSection';
export { AboutSection } from './sections/AboutSection';
export type { ConsoleSectionId, ConsoleSectionDef } from './types';
